// Code generated by make; DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.2
// source: cosi.proto

package cosi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// S3SignatureVersion is the version of the signing algorithm for all s3 requests
type S3SignatureVersion int32

const (
	S3SignatureVersion_UnknownSignature S3SignatureVersion = 0
	// S3V2, Signature version v2
	S3SignatureVersion_S3V2 S3SignatureVersion = 1
	// S3V4, Signature version v4
	S3SignatureVersion_S3V4 S3SignatureVersion = 2
)

// Enum value maps for S3SignatureVersion.
var (
	S3SignatureVersion_name = map[int32]string{
		0: "UnknownSignature",
		1: "S3V2",
		2: "S3V4",
	}
	S3SignatureVersion_value = map[string]int32{
		"UnknownSignature": 0,
		"S3V2":             1,
		"S3V4":             2,
	}
)

func (x S3SignatureVersion) Enum() *S3SignatureVersion {
	p := new(S3SignatureVersion)
	*p = x
	return p
}

func (x S3SignatureVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (S3SignatureVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_cosi_proto_enumTypes[0].Descriptor()
}

func (S3SignatureVersion) Type() protoreflect.EnumType {
	return &file_cosi_proto_enumTypes[0]
}

func (x S3SignatureVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use S3SignatureVersion.Descriptor instead.
func (S3SignatureVersion) EnumDescriptor() ([]byte, []int) {
	return file_cosi_proto_rawDescGZIP(), []int{0}
}

type AnonymousBucketAccessMode int32

const (
	AnonymousBucketAccessMode_UnknownBucketAccessMode AnonymousBucketAccessMode = 0
	// Default, disallow uncredentialed access to the backend storage.
	AnonymousBucketAccessMode_Private AnonymousBucketAccessMode = 1
	// Read only, uncredentialed users can call ListBucket and GetObject.
	AnonymousBucketAccessMode_ReadOnly AnonymousBucketAccessMode = 2
	// Write only, uncredentialed users can only call PutObject.
	AnonymousBucketAccessMode_WriteOnly AnonymousBucketAccessMode = 3
	// Read/Write, uncredentialed users can read objects as well as PutObject.
	AnonymousBucketAccessMode_ReadWrite AnonymousBucketAccessMode = 4
)

// Enum value maps for AnonymousBucketAccessMode.
var (
	AnonymousBucketAccessMode_name = map[int32]string{
		0: "UnknownBucketAccessMode",
		1: "Private",
		2: "ReadOnly",
		3: "WriteOnly",
		4: "ReadWrite",
	}
	AnonymousBucketAccessMode_value = map[string]int32{
		"UnknownBucketAccessMode": 0,
		"Private":                 1,
		"ReadOnly":                2,
		"WriteOnly":               3,
		"ReadWrite":               4,
	}
)

func (x AnonymousBucketAccessMode) Enum() *AnonymousBucketAccessMode {
	p := new(AnonymousBucketAccessMode)
	*p = x
	return p
}

func (x AnonymousBucketAccessMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnonymousBucketAccessMode) Descriptor() protoreflect.EnumDescriptor {
	return file_cosi_proto_enumTypes[1].Descriptor()
}

func (AnonymousBucketAccessMode) Type() protoreflect.EnumType {
	return &file_cosi_proto_enumTypes[1]
}

func (x AnonymousBucketAccessMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnonymousBucketAccessMode.Descriptor instead.
func (AnonymousBucketAccessMode) EnumDescriptor() ([]byte, []int) {
	return file_cosi_proto_rawDescGZIP(), []int{1}
}

type AuthenticationType int32

const (
	AuthenticationType_UnknownAuthenticationType AuthenticationType = 0
	// Default, KEY based authentication.
	AuthenticationType_Key AuthenticationType = 1
	// Storageaccount based authentication.
	AuthenticationType_IAM AuthenticationType = 2
)

// Enum value maps for AuthenticationType.
var (
	AuthenticationType_name = map[int32]string{
		0: "UnknownAuthenticationType",
		1: "Key",
		2: "IAM",
	}
	AuthenticationType_value = map[string]int32{
		"UnknownAuthenticationType": 0,
		"Key":                       1,
		"IAM":                       2,
	}
)

func (x AuthenticationType) Enum() *AuthenticationType {
	p := new(AuthenticationType)
	*p = x
	return p
}

func (x AuthenticationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthenticationType) Descriptor() protoreflect.EnumDescriptor {
	return file_cosi_proto_enumTypes[2].Descriptor()
}

func (AuthenticationType) Type() protoreflect.EnumType {
	return &file_cosi_proto_enumTypes[2]
}

func (x AuthenticationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthenticationType.Descriptor instead.
func (AuthenticationType) EnumDescriptor() ([]byte, []int) {
	return file_cosi_proto_rawDescGZIP(), []int{2}
}

type S3 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// region denotes the geographical region where the S3 server is running
	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	// signature_version denotes the signature version for signing all s3 requests
	SignatureVersion S3SignatureVersion `protobuf:"varint,2,opt,name=signature_version,json=signatureVersion,proto3,enum=cosi.v1alpha1.S3SignatureVersion" json:"signature_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *S3) Reset() {
	*x = S3{}
	mi := &file_cosi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3) ProtoMessage() {}

func (x *S3) ProtoReflect() protoreflect.Message {
	mi := &file_cosi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3.ProtoReflect.Descriptor instead.
func (*S3) Descriptor() ([]byte, []int) {
	return file_cosi_proto_rawDescGZIP(), []int{0}
}

func (x *S3) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *S3) GetSignatureVersion() S3SignatureVersion {
	if x != nil {
		return x.SignatureVersion
	}
	return S3SignatureVersion_UnknownSignature
}

type AzureBlob struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// storage_account is the id of the azure storage account
	StorageAccount string `protobuf:"bytes,1,opt,name=storage_account,json=storageAccount,proto3" json:"storage_account,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AzureBlob) Reset() {
	*x = AzureBlob{}
	mi := &file_cosi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureBlob) ProtoMessage() {}

func (x *AzureBlob) ProtoReflect() protoreflect.Message {
	mi := &file_cosi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureBlob.ProtoReflect.Descriptor instead.
func (*AzureBlob) Descriptor() ([]byte, []int) {
	return file_cosi_proto_rawDescGZIP(), []int{1}
}

func (x *AzureBlob) GetStorageAccount() string {
	if x != nil {
		return x.StorageAccount
	}
	return ""
}

type GCS struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// private_key_name denotes the name of the private key in the storage backend
	PrivateKeyName string `protobuf:"bytes,1,opt,name=private_key_name,json=privateKeyName,proto3" json:"private_key_name,omitempty"`
	// project_id denotes the name of the project id in the storage backend
	ProjectId string `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// service_account denotes the name of the service account in the storage backend
	ServiceAccount string `protobuf:"bytes,3,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GCS) Reset() {
	*x = GCS{}
	mi := &file_cosi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GCS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCS) ProtoMessage() {}

func (x *GCS) ProtoReflect() protoreflect.Message {
	mi := &file_cosi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCS.ProtoReflect.Descriptor instead.
func (*GCS) Descriptor() ([]byte, []int) {
	return file_cosi_proto_rawDescGZIP(), []int{2}
}

func (x *GCS) GetPrivateKeyName() string {
	if x != nil {
		return x.PrivateKeyName
	}
	return ""
}

func (x *GCS) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GCS) GetServiceAccount() string {
	if x != nil {
		return x.ServiceAccount
	}
	return ""
}

type Protocol struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*Protocol_S3
	//	*Protocol_AzureBlob
	//	*Protocol_Gcs
	Type          isProtocol_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Protocol) Reset() {
	*x = Protocol{}
	mi := &file_cosi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Protocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Protocol) ProtoMessage() {}

func (x *Protocol) ProtoReflect() protoreflect.Message {
	mi := &file_cosi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Protocol.ProtoReflect.Descriptor instead.
func (*Protocol) Descriptor() ([]byte, []int) {
	return file_cosi_proto_rawDescGZIP(), []int{3}
}

func (x *Protocol) GetType() isProtocol_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Protocol) GetS3() *S3 {
	if x != nil {
		if x, ok := x.Type.(*Protocol_S3); ok {
			return x.S3
		}
	}
	return nil
}

func (x *Protocol) GetAzureBlob() *AzureBlob {
	if x != nil {
		if x, ok := x.Type.(*Protocol_AzureBlob); ok {
			return x.AzureBlob
		}
	}
	return nil
}

func (x *Protocol) GetGcs() *GCS {
	if x != nil {
		if x, ok := x.Type.(*Protocol_Gcs); ok {
			return x.Gcs
		}
	}
	return nil
}

type isProtocol_Type interface {
	isProtocol_Type()
}

type Protocol_S3 struct {
	S3 *S3 `protobuf:"bytes,1,opt,name=s3,proto3,oneof"`
}

type Protocol_AzureBlob struct {
	AzureBlob *AzureBlob `protobuf:"bytes,2,opt,name=azureBlob,proto3,oneof"`
}

type Protocol_Gcs struct {
	Gcs *GCS `protobuf:"bytes,3,opt,name=gcs,proto3,oneof"`
}

func (*Protocol_S3) isProtocol_Type() {}

func (*Protocol_AzureBlob) isProtocol_Type() {}

func (*Protocol_Gcs) isProtocol_Type() {}

type CredentialDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// map of the details in the secrets for the protocol string
	Secrets       map[string]string `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialDetails) Reset() {
	*x = CredentialDetails{}
	mi := &file_cosi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialDetails) ProtoMessage() {}

func (x *CredentialDetails) ProtoReflect() protoreflect.Message {
	mi := &file_cosi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialDetails.ProtoReflect.Descriptor instead.
func (*CredentialDetails) Descriptor() ([]byte, []int) {
	return file_cosi_proto_rawDescGZIP(), []int{4}
}

func (x *CredentialDetails) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type DriverGetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverGetInfoRequest) Reset() {
	*x = DriverGetInfoRequest{}
	mi := &file_cosi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverGetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverGetInfoRequest) ProtoMessage() {}

func (x *DriverGetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cosi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverGetInfoRequest.ProtoReflect.Descriptor instead.
func (*DriverGetInfoRequest) Descriptor() ([]byte, []int) {
	return file_cosi_proto_rawDescGZIP(), []int{5}
}

type DriverGetInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This field is REQUIRED
	// The name MUST follow domain name notation format
	// (https://tools.ietf.org/html/rfc1035#section-2.3.1). It SHOULD
	// include the plugin's host company name and the plugin name,
	// to minimize the possibility of collisions. It MUST be 63
	// characters or less, beginning and ending with an alphanumeric
	// character ([a-z0-9A-Z]) with dashes (-), dots (.), and
	// alphanumerics between.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverGetInfoResponse) Reset() {
	*x = DriverGetInfoResponse{}
	mi := &file_cosi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverGetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverGetInfoResponse) ProtoMessage() {}

func (x *DriverGetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cosi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverGetInfoResponse.ProtoReflect.Descriptor instead.
func (*DriverGetInfoResponse) Descriptor() ([]byte, []int) {
	return file_cosi_proto_rawDescGZIP(), []int{6}
}

func (x *DriverGetInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DriverCreateBucketRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This field is REQUIRED
	// name specifies the name of the bucket that should be created.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// This field is OPTIONAL
	// The caller should treat the values in parameters as opaque.
	// The receiver is responsible for parsing and validating the values.
	Parameters    map[string]string `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverCreateBucketRequest) Reset() {
	*x = DriverCreateBucketRequest{}
	mi := &file_cosi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverCreateBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverCreateBucketRequest) ProtoMessage() {}

func (x *DriverCreateBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cosi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverCreateBucketRequest.ProtoReflect.Descriptor instead.
func (*DriverCreateBucketRequest) Descriptor() ([]byte, []int) {
	return file_cosi_proto_rawDescGZIP(), []int{7}
}

func (x *DriverCreateBucketRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DriverCreateBucketRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type DriverCreateBucketResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// bucket_id returned here is expected to be the globally unique
	// identifier for the bucket in the object storage provider.
	BucketId string `protobuf:"bytes,1,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	// bucket_info returned here stores the data specific to the
	// bucket required by the object storage provider to connect to the bucket.
	BucketInfo    *Protocol `protobuf:"bytes,2,opt,name=bucket_info,json=bucketInfo,proto3" json:"bucket_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverCreateBucketResponse) Reset() {
	*x = DriverCreateBucketResponse{}
	mi := &file_cosi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverCreateBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverCreateBucketResponse) ProtoMessage() {}

func (x *DriverCreateBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cosi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverCreateBucketResponse.ProtoReflect.Descriptor instead.
func (*DriverCreateBucketResponse) Descriptor() ([]byte, []int) {
	return file_cosi_proto_rawDescGZIP(), []int{8}
}

func (x *DriverCreateBucketResponse) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *DriverCreateBucketResponse) GetBucketInfo() *Protocol {
	if x != nil {
		return x.BucketInfo
	}
	return nil
}

type DriverDeleteBucketRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This field is REQUIRED
	// bucket_id is a globally unique identifier for the bucket
	// in the object storage provider
	BucketId string `protobuf:"bytes,1,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	// This field is OPTIONAL
	// The caller should treat the values in delete_context as opaque.
	// The receiver is responsible for parsing and validating the values.
	DeleteContext map[string]string `protobuf:"bytes,2,rep,name=delete_context,json=deleteContext,proto3" json:"delete_context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverDeleteBucketRequest) Reset() {
	*x = DriverDeleteBucketRequest{}
	mi := &file_cosi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverDeleteBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverDeleteBucketRequest) ProtoMessage() {}

func (x *DriverDeleteBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cosi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverDeleteBucketRequest.ProtoReflect.Descriptor instead.
func (*DriverDeleteBucketRequest) Descriptor() ([]byte, []int) {
	return file_cosi_proto_rawDescGZIP(), []int{9}
}

func (x *DriverDeleteBucketRequest) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *DriverDeleteBucketRequest) GetDeleteContext() map[string]string {
	if x != nil {
		return x.DeleteContext
	}
	return nil
}

type DriverDeleteBucketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverDeleteBucketResponse) Reset() {
	*x = DriverDeleteBucketResponse{}
	mi := &file_cosi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverDeleteBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverDeleteBucketResponse) ProtoMessage() {}

func (x *DriverDeleteBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cosi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverDeleteBucketResponse.ProtoReflect.Descriptor instead.
func (*DriverDeleteBucketResponse) Descriptor() ([]byte, []int) {
	return file_cosi_proto_rawDescGZIP(), []int{10}
}

type DriverGrantBucketAccessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This field is REQUIRED
	// bucket_id is a globally unique identifier for the bucket
	// in the object storage provider
	BucketId string `protobuf:"bytes,1,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	// This field is REQUIRED
	// name field is used to define the name of the bucket access object.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// This field is REQUIRED
	// Requested authentication type for the bucket access.
	// Supported authentication types are KEY or IAM.
	AuthenticationType AuthenticationType `protobuf:"varint,3,opt,name=authentication_type,json=authenticationType,proto3,enum=cosi.v1alpha1.AuthenticationType" json:"authentication_type,omitempty"`
	// This field is OPTIONAL
	// The caller should treat the values in parameters as opaque.
	// The receiver is responsible for parsing and validating the values.
	Parameters    map[string]string `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverGrantBucketAccessRequest) Reset() {
	*x = DriverGrantBucketAccessRequest{}
	mi := &file_cosi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverGrantBucketAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverGrantBucketAccessRequest) ProtoMessage() {}

func (x *DriverGrantBucketAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cosi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverGrantBucketAccessRequest.ProtoReflect.Descriptor instead.
func (*DriverGrantBucketAccessRequest) Descriptor() ([]byte, []int) {
	return file_cosi_proto_rawDescGZIP(), []int{11}
}

func (x *DriverGrantBucketAccessRequest) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *DriverGrantBucketAccessRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DriverGrantBucketAccessRequest) GetAuthenticationType() AuthenticationType {
	if x != nil {
		return x.AuthenticationType
	}
	return AuthenticationType_UnknownAuthenticationType
}

func (x *DriverGrantBucketAccessRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type DriverGrantBucketAccessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This field is REQUIRED
	// This is the account_id that is being provided access. This will
	// be required later to revoke access.
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// This field is REQUIRED
	// Credentials supplied for accessing the bucket ex: aws access key id and secret, etc.
	Credentials   map[string]*CredentialDetails `protobuf:"bytes,2,rep,name=credentials,proto3" json:"credentials,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverGrantBucketAccessResponse) Reset() {
	*x = DriverGrantBucketAccessResponse{}
	mi := &file_cosi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverGrantBucketAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverGrantBucketAccessResponse) ProtoMessage() {}

func (x *DriverGrantBucketAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cosi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverGrantBucketAccessResponse.ProtoReflect.Descriptor instead.
func (*DriverGrantBucketAccessResponse) Descriptor() ([]byte, []int) {
	return file_cosi_proto_rawDescGZIP(), []int{12}
}

func (x *DriverGrantBucketAccessResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *DriverGrantBucketAccessResponse) GetCredentials() map[string]*CredentialDetails {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type DriverRevokeBucketAccessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This field is REQUIRED
	// bucket_id is a globally unique identifier for the bucket
	// in the object storage provider.
	BucketId string `protobuf:"bytes,1,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	// This field is REQUIRED
	// This is the account_id that is having its access revoked.
	AccountId string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// This field is OPTIONAL
	// The caller should treat the values in revoke_access_context as opaque.
	// The receiver is responsible for parsing and validating the values.
	RevokeAccessContext map[string]string `protobuf:"bytes,3,rep,name=revoke_access_context,json=revokeAccessContext,proto3" json:"revoke_access_context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DriverRevokeBucketAccessRequest) Reset() {
	*x = DriverRevokeBucketAccessRequest{}
	mi := &file_cosi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverRevokeBucketAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverRevokeBucketAccessRequest) ProtoMessage() {}

func (x *DriverRevokeBucketAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cosi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverRevokeBucketAccessRequest.ProtoReflect.Descriptor instead.
func (*DriverRevokeBucketAccessRequest) Descriptor() ([]byte, []int) {
	return file_cosi_proto_rawDescGZIP(), []int{13}
}

func (x *DriverRevokeBucketAccessRequest) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *DriverRevokeBucketAccessRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *DriverRevokeBucketAccessRequest) GetRevokeAccessContext() map[string]string {
	if x != nil {
		return x.RevokeAccessContext
	}
	return nil
}

type DriverRevokeBucketAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverRevokeBucketAccessResponse) Reset() {
	*x = DriverRevokeBucketAccessResponse{}
	mi := &file_cosi_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverRevokeBucketAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverRevokeBucketAccessResponse) ProtoMessage() {}

func (x *DriverRevokeBucketAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cosi_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverRevokeBucketAccessResponse.ProtoReflect.Descriptor instead.
func (*DriverRevokeBucketAccessResponse) Descriptor() ([]byte, []int) {
	return file_cosi_proto_rawDescGZIP(), []int{14}
}

var file_cosi_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1116,
		Name:          "cosi.v1alpha1.alpha_enum",
		Tag:           "varint,1116,opt,name=alpha_enum",
		Filename:      "cosi.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1116,
		Name:          "cosi.v1alpha1.alpha_enum_value",
		Tag:           "varint,1116,opt,name=alpha_enum_value",
		Filename:      "cosi.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1115,
		Name:          "cosi.v1alpha1.cosi_secret",
		Tag:           "varint,1115,opt,name=cosi_secret",
		Filename:      "cosi.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1116,
		Name:          "cosi.v1alpha1.alpha_field",
		Tag:           "varint,1116,opt,name=alpha_field",
		Filename:      "cosi.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1116,
		Name:          "cosi.v1alpha1.alpha_message",
		Tag:           "varint,1116,opt,name=alpha_message",
		Filename:      "cosi.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1116,
		Name:          "cosi.v1alpha1.alpha_method",
		Tag:           "varint,1116,opt,name=alpha_method",
		Filename:      "cosi.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1116,
		Name:          "cosi.v1alpha1.alpha_service",
		Tag:           "varint,1116,opt,name=alpha_service",
		Filename:      "cosi.proto",
	},
}

// Extension fields to descriptorpb.EnumOptions.
var (
	// Indicates that this enum is OPTIONAL and part of an experimental
	// API that may be deprecated and eventually removed between minor
	// releases.
	//
	// optional bool alpha_enum = 1116;
	E_AlphaEnum = &file_cosi_proto_extTypes[0]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// Indicates that this enum value is OPTIONAL and part of an
	// experimental API that may be deprecated and eventually removed
	// between minor releases.
	//
	// optional bool alpha_enum_value = 1116;
	E_AlphaEnumValue = &file_cosi_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// Indicates that a field MAY contain information that is sensitive
	// and MUST be treated as such (e.g. not logged).
	//
	// optional bool cosi_secret = 1115;
	E_CosiSecret = &file_cosi_proto_extTypes[2]
	// Indicates that this field is OPTIONAL and part of an experimental
	// API that may be deprecated and eventually removed between minor
	// releases.
	//
	// optional bool alpha_field = 1116;
	E_AlphaField = &file_cosi_proto_extTypes[3]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// Indicates that this message is OPTIONAL and part of an experimental
	// API that may be deprecated and eventually removed between minor
	// releases.
	//
	// optional bool alpha_message = 1116;
	E_AlphaMessage = &file_cosi_proto_extTypes[4]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// Indicates that this method is OPTIONAL and part of an experimental
	// API that may be deprecated and eventually removed between minor
	// releases.
	//
	// optional bool alpha_method = 1116;
	E_AlphaMethod = &file_cosi_proto_extTypes[5]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// Indicates that this service is OPTIONAL and part of an experimental
	// API that may be deprecated and eventually removed between minor
	// releases.
	//
	// optional bool alpha_service = 1116;
	E_AlphaService = &file_cosi_proto_extTypes[6]
)

var File_cosi_proto protoreflect.FileDescriptor

const file_cosi_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"cosi.proto\x12\rcosi.v1alpha1\x1a google/protobuf/descriptor.proto\"l\n" +
	"\x02S3\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12N\n" +
	"\x11signature_version\x18\x02 \x01(\x0e2!.cosi.v1alpha1.S3SignatureVersionR\x10signatureVersion\"4\n" +
	"\tAzureBlob\x12'\n" +
	"\x0fstorage_account\x18\x01 \x01(\tR\x0estorageAccount\"w\n" +
	"\x03GCS\x12(\n" +
	"\x10private_key_name\x18\x01 \x01(\tR\x0eprivateKeyName\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12'\n" +
	"\x0fservice_account\x18\x03 \x01(\tR\x0eserviceAccount\"\x99\x01\n" +
	"\bProtocol\x12#\n" +
	"\x02s3\x18\x01 \x01(\v2\x11.cosi.v1alpha1.S3H\x00R\x02s3\x128\n" +
	"\tazureBlob\x18\x02 \x01(\v2\x18.cosi.v1alpha1.AzureBlobH\x00R\tazureBlob\x12&\n" +
	"\x03gcs\x18\x03 \x01(\v2\x12.cosi.v1alpha1.GCSH\x00R\x03gcsB\x06\n" +
	"\x04type\"\x98\x01\n" +
	"\x11CredentialDetails\x12G\n" +
	"\asecrets\x18\x01 \x03(\v2-.cosi.v1alpha1.CredentialDetails.SecretsEntryR\asecrets\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x16\n" +
	"\x14DriverGetInfoRequest\"+\n" +
	"\x15DriverGetInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xc8\x01\n" +
	"\x19DriverCreateBucketRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12X\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v28.cosi.v1alpha1.DriverCreateBucketRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"s\n" +
	"\x1aDriverCreateBucketResponse\x12\x1b\n" +
	"\tbucket_id\x18\x01 \x01(\tR\bbucketId\x128\n" +
	"\vbucket_info\x18\x02 \x01(\v2\x17.cosi.v1alpha1.ProtocolR\n" +
	"bucketInfo\"\xde\x01\n" +
	"\x19DriverDeleteBucketRequest\x12\x1b\n" +
	"\tbucket_id\x18\x01 \x01(\tR\bbucketId\x12b\n" +
	"\x0edelete_context\x18\x02 \x03(\v2;.cosi.v1alpha1.DriverDeleteBucketRequest.DeleteContextEntryR\rdeleteContext\x1a@\n" +
	"\x12DeleteContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1c\n" +
	"\x1aDriverDeleteBucketResponse\"\xc3\x02\n" +
	"\x1eDriverGrantBucketAccessRequest\x12\x1b\n" +
	"\tbucket_id\x18\x01 \x01(\tR\bbucketId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12R\n" +
	"\x13authentication_type\x18\x03 \x01(\x0e2!.cosi.v1alpha1.AuthenticationTypeR\x12authenticationType\x12]\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2=.cosi.v1alpha1.DriverGrantBucketAccessRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x85\x02\n" +
	"\x1fDriverGrantBucketAccessResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12a\n" +
	"\vcredentials\x18\x02 \x03(\v2?.cosi.v1alpha1.DriverGrantBucketAccessResponse.CredentialsEntryR\vcredentials\x1a`\n" +
	"\x10CredentialsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .cosi.v1alpha1.CredentialDetailsR\x05value:\x028\x01\"\xa2\x02\n" +
	"\x1fDriverRevokeBucketAccessRequest\x12\x1b\n" +
	"\tbucket_id\x18\x01 \x01(\tR\bbucketId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12{\n" +
	"\x15revoke_access_context\x18\x03 \x03(\v2G.cosi.v1alpha1.DriverRevokeBucketAccessRequest.RevokeAccessContextEntryR\x13revokeAccessContext\x1aF\n" +
	"\x18RevokeAccessContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\"\n" +
	" DriverRevokeBucketAccessResponse*>\n" +
	"\x12S3SignatureVersion\x12\x14\n" +
	"\x10UnknownSignature\x10\x00\x12\b\n" +
	"\x04S3V2\x10\x01\x12\b\n" +
	"\x04S3V4\x10\x02*q\n" +
	"\x19AnonymousBucketAccessMode\x12\x1b\n" +
	"\x17UnknownBucketAccessMode\x10\x00\x12\v\n" +
	"\aPrivate\x10\x01\x12\f\n" +
	"\bReadOnly\x10\x02\x12\r\n" +
	"\tWriteOnly\x10\x03\x12\r\n" +
	"\tReadWrite\x10\x04*E\n" +
	"\x12AuthenticationType\x12\x1d\n" +
	"\x19UnknownAuthenticationType\x10\x00\x12\a\n" +
	"\x03Key\x10\x01\x12\a\n" +
	"\x03IAM\x10\x022h\n" +
	"\bIdentity\x12\\\n" +
	"\rDriverGetInfo\x12#.cosi.v1alpha1.DriverGetInfoRequest\x1a$.cosi.v1alpha1.DriverGetInfoResponse\"\x002\xde\x03\n" +
	"\vProvisioner\x12k\n" +
	"\x12DriverCreateBucket\x12(.cosi.v1alpha1.DriverCreateBucketRequest\x1a).cosi.v1alpha1.DriverCreateBucketResponse\"\x00\x12k\n" +
	"\x12DriverDeleteBucket\x12(.cosi.v1alpha1.DriverDeleteBucketRequest\x1a).cosi.v1alpha1.DriverDeleteBucketResponse\"\x00\x12x\n" +
	"\x17DriverGrantBucketAccess\x12-.cosi.v1alpha1.DriverGrantBucketAccessRequest\x1a..cosi.v1alpha1.DriverGrantBucketAccessResponse\x12{\n" +
	"\x18DriverRevokeBucketAccess\x12..cosi.v1alpha1.DriverRevokeBucketAccessRequest\x1a/.cosi.v1alpha1.DriverRevokeBucketAccessResponse:<\n" +
	"\n" +
	"alpha_enum\x12\x1c.google.protobuf.EnumOptions\x18\xdc\b \x01(\bR\talphaEnum:L\n" +
	"\x10alpha_enum_value\x12!.google.protobuf.EnumValueOptions\x18\xdc\b \x01(\bR\x0ealphaEnumValue:?\n" +
	"\vcosi_secret\x12\x1d.google.protobuf.FieldOptions\x18\xdb\b \x01(\bR\n" +
	"cosiSecret:?\n" +
	"\valpha_field\x12\x1d.google.protobuf.FieldOptions\x18\xdc\b \x01(\bR\n" +
	"alphaField:E\n" +
	"\ralpha_message\x12\x1f.google.protobuf.MessageOptions\x18\xdc\b \x01(\bR\falphaMessage:B\n" +
	"\falpha_method\x12\x1e.google.protobuf.MethodOptions\x18\xdc\b \x01(\bR\valphaMethod:E\n" +
	"\ralpha_service\x12\x1f.google.protobuf.ServiceOptions\x18\xdc\b \x01(\bR\falphaServiceB;Z9sigs.k8s.io/container-object-storage-interface/proto;cosib\x06proto3"

var (
	file_cosi_proto_rawDescOnce sync.Once
	file_cosi_proto_rawDescData []byte
)

func file_cosi_proto_rawDescGZIP() []byte {
	file_cosi_proto_rawDescOnce.Do(func() {
		file_cosi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cosi_proto_rawDesc), len(file_cosi_proto_rawDesc)))
	})
	return file_cosi_proto_rawDescData
}

var file_cosi_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_cosi_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_cosi_proto_goTypes = []any{
	(S3SignatureVersion)(0),                  // 0: cosi.v1alpha1.S3SignatureVersion
	(AnonymousBucketAccessMode)(0),           // 1: cosi.v1alpha1.AnonymousBucketAccessMode
	(AuthenticationType)(0),                  // 2: cosi.v1alpha1.AuthenticationType
	(*S3)(nil),                               // 3: cosi.v1alpha1.S3
	(*AzureBlob)(nil),                        // 4: cosi.v1alpha1.AzureBlob
	(*GCS)(nil),                              // 5: cosi.v1alpha1.GCS
	(*Protocol)(nil),                         // 6: cosi.v1alpha1.Protocol
	(*CredentialDetails)(nil),                // 7: cosi.v1alpha1.CredentialDetails
	(*DriverGetInfoRequest)(nil),             // 8: cosi.v1alpha1.DriverGetInfoRequest
	(*DriverGetInfoResponse)(nil),            // 9: cosi.v1alpha1.DriverGetInfoResponse
	(*DriverCreateBucketRequest)(nil),        // 10: cosi.v1alpha1.DriverCreateBucketRequest
	(*DriverCreateBucketResponse)(nil),       // 11: cosi.v1alpha1.DriverCreateBucketResponse
	(*DriverDeleteBucketRequest)(nil),        // 12: cosi.v1alpha1.DriverDeleteBucketRequest
	(*DriverDeleteBucketResponse)(nil),       // 13: cosi.v1alpha1.DriverDeleteBucketResponse
	(*DriverGrantBucketAccessRequest)(nil),   // 14: cosi.v1alpha1.DriverGrantBucketAccessRequest
	(*DriverGrantBucketAccessResponse)(nil),  // 15: cosi.v1alpha1.DriverGrantBucketAccessResponse
	(*DriverRevokeBucketAccessRequest)(nil),  // 16: cosi.v1alpha1.DriverRevokeBucketAccessRequest
	(*DriverRevokeBucketAccessResponse)(nil), // 17: cosi.v1alpha1.DriverRevokeBucketAccessResponse
	nil,                                      // 18: cosi.v1alpha1.CredentialDetails.SecretsEntry
	nil,                                      // 19: cosi.v1alpha1.DriverCreateBucketRequest.ParametersEntry
	nil,                                      // 20: cosi.v1alpha1.DriverDeleteBucketRequest.DeleteContextEntry
	nil,                                      // 21: cosi.v1alpha1.DriverGrantBucketAccessRequest.ParametersEntry
	nil,                                      // 22: cosi.v1alpha1.DriverGrantBucketAccessResponse.CredentialsEntry
	nil,                                      // 23: cosi.v1alpha1.DriverRevokeBucketAccessRequest.RevokeAccessContextEntry
	(*descriptorpb.EnumOptions)(nil),         // 24: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil),    // 25: google.protobuf.EnumValueOptions
	(*descriptorpb.FieldOptions)(nil),        // 26: google.protobuf.FieldOptions
	(*descriptorpb.MessageOptions)(nil),      // 27: google.protobuf.MessageOptions
	(*descriptorpb.MethodOptions)(nil),       // 28: google.protobuf.MethodOptions
	(*descriptorpb.ServiceOptions)(nil),      // 29: google.protobuf.ServiceOptions
}
var file_cosi_proto_depIdxs = []int32{
	0,  // 0: cosi.v1alpha1.S3.signature_version:type_name -> cosi.v1alpha1.S3SignatureVersion
	3,  // 1: cosi.v1alpha1.Protocol.s3:type_name -> cosi.v1alpha1.S3
	4,  // 2: cosi.v1alpha1.Protocol.azureBlob:type_name -> cosi.v1alpha1.AzureBlob
	5,  // 3: cosi.v1alpha1.Protocol.gcs:type_name -> cosi.v1alpha1.GCS
	18, // 4: cosi.v1alpha1.CredentialDetails.secrets:type_name -> cosi.v1alpha1.CredentialDetails.SecretsEntry
	19, // 5: cosi.v1alpha1.DriverCreateBucketRequest.parameters:type_name -> cosi.v1alpha1.DriverCreateBucketRequest.ParametersEntry
	6,  // 6: cosi.v1alpha1.DriverCreateBucketResponse.bucket_info:type_name -> cosi.v1alpha1.Protocol
	20, // 7: cosi.v1alpha1.DriverDeleteBucketRequest.delete_context:type_name -> cosi.v1alpha1.DriverDeleteBucketRequest.DeleteContextEntry
	2,  // 8: cosi.v1alpha1.DriverGrantBucketAccessRequest.authentication_type:type_name -> cosi.v1alpha1.AuthenticationType
	21, // 9: cosi.v1alpha1.DriverGrantBucketAccessRequest.parameters:type_name -> cosi.v1alpha1.DriverGrantBucketAccessRequest.ParametersEntry
	22, // 10: cosi.v1alpha1.DriverGrantBucketAccessResponse.credentials:type_name -> cosi.v1alpha1.DriverGrantBucketAccessResponse.CredentialsEntry
	23, // 11: cosi.v1alpha1.DriverRevokeBucketAccessRequest.revoke_access_context:type_name -> cosi.v1alpha1.DriverRevokeBucketAccessRequest.RevokeAccessContextEntry
	7,  // 12: cosi.v1alpha1.DriverGrantBucketAccessResponse.CredentialsEntry.value:type_name -> cosi.v1alpha1.CredentialDetails
	24, // 13: cosi.v1alpha1.alpha_enum:extendee -> google.protobuf.EnumOptions
	25, // 14: cosi.v1alpha1.alpha_enum_value:extendee -> google.protobuf.EnumValueOptions
	26, // 15: cosi.v1alpha1.cosi_secret:extendee -> google.protobuf.FieldOptions
	26, // 16: cosi.v1alpha1.alpha_field:extendee -> google.protobuf.FieldOptions
	27, // 17: cosi.v1alpha1.alpha_message:extendee -> google.protobuf.MessageOptions
	28, // 18: cosi.v1alpha1.alpha_method:extendee -> google.protobuf.MethodOptions
	29, // 19: cosi.v1alpha1.alpha_service:extendee -> google.protobuf.ServiceOptions
	8,  // 20: cosi.v1alpha1.Identity.DriverGetInfo:input_type -> cosi.v1alpha1.DriverGetInfoRequest
	10, // 21: cosi.v1alpha1.Provisioner.DriverCreateBucket:input_type -> cosi.v1alpha1.DriverCreateBucketRequest
	12, // 22: cosi.v1alpha1.Provisioner.DriverDeleteBucket:input_type -> cosi.v1alpha1.DriverDeleteBucketRequest
	14, // 23: cosi.v1alpha1.Provisioner.DriverGrantBucketAccess:input_type -> cosi.v1alpha1.DriverGrantBucketAccessRequest
	16, // 24: cosi.v1alpha1.Provisioner.DriverRevokeBucketAccess:input_type -> cosi.v1alpha1.DriverRevokeBucketAccessRequest
	9,  // 25: cosi.v1alpha1.Identity.DriverGetInfo:output_type -> cosi.v1alpha1.DriverGetInfoResponse
	11, // 26: cosi.v1alpha1.Provisioner.DriverCreateBucket:output_type -> cosi.v1alpha1.DriverCreateBucketResponse
	13, // 27: cosi.v1alpha1.Provisioner.DriverDeleteBucket:output_type -> cosi.v1alpha1.DriverDeleteBucketResponse
	15, // 28: cosi.v1alpha1.Provisioner.DriverGrantBucketAccess:output_type -> cosi.v1alpha1.DriverGrantBucketAccessResponse
	17, // 29: cosi.v1alpha1.Provisioner.DriverRevokeBucketAccess:output_type -> cosi.v1alpha1.DriverRevokeBucketAccessResponse
	25, // [25:30] is the sub-list for method output_type
	20, // [20:25] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	13, // [13:20] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_cosi_proto_init() }
func file_cosi_proto_init() {
	if File_cosi_proto != nil {
		return
	}
	file_cosi_proto_msgTypes[3].OneofWrappers = []any{
		(*Protocol_S3)(nil),
		(*Protocol_AzureBlob)(nil),
		(*Protocol_Gcs)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cosi_proto_rawDesc), len(file_cosi_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   21,
			NumExtensions: 7,
			NumServices:   2,
		},
		GoTypes:           file_cosi_proto_goTypes,
		DependencyIndexes: file_cosi_proto_depIdxs,
		EnumInfos:         file_cosi_proto_enumTypes,
		MessageInfos:      file_cosi_proto_msgTypes,
		ExtensionInfos:    file_cosi_proto_extTypes,
	}.Build()
	File_cosi_proto = out.File
	file_cosi_proto_goTypes = nil
	file_cosi_proto_depIdxs = nil
}
